### ISSUE TITLE
404 error when recommender fails to find results

### ISSUE THREAD

**Issue by taylorshaulis** [adsabs/recommender_service#52]
Either the recommender was unable to perform it's lookup or it did not find any results.

[2017-09-26 15:50:37,985] ERROR in views: Recommender failed (2018FrPhy..13.9801W): Unable to get results!

If the issue was executing the lookup, does this use postgres or solr?

If the problem is that there is no entry for 2018FrPhy..13.9801W can we please have this generate a 2XX http status code? Maybe the respone could be something like entry not found, but the 404 status code will eventually have a negative impact on user's reputation

**Comment by ehenneken** [comment]
Since this service is discontinued, I'm closing this issue.
